### ISSUE TITLE
Corrección primera entrega

### ISSUE THREAD

**Issue by Natygimep** [brianlider/K2002-Grupo15#1]
- Arreglar depósito con max

- Mejorar el upgrade con min

- Mejorar queda igual con id

- Sacar las guardas sobrantes

- Está bien, falta orden superior

**Comment by qmarquez** [comment]
+ Corregir los test para que usen las funcionalidades que crean despues
+ Ver los point free
+ Para buscar un elemento de una lista aplicar el find (peorBloque, masAdinerado, menosAdinerado)
+ Mas abstracción de las coasas
